runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v1
      with:
        java-version: "12.x"
    - name: build release 
      uses: subosito/flutter-action@v1
      with:
        channel: "stable"
    - name: install dependencies
      shell: bash
      run: flutter pub get