on:
  workflow_call:
    secrets:
      firebase_options:
        requered: true
      google_services:
        requered: true
      key_properties:
        requered: true
        

jobs:
  setup_secret_files:
    name: Setup secret files
    runs-on: ubuntu-latest
    steps:
      - name: create firebase options
        uses: 1arp/create-a-file-action@0.2
        with:
          path: 'lib'
          file: 'firebase_options.dart'
          content: ${{ secrets.firebase_options}}
      - name: create google services
        uses: 1arp/create-a-file-action@0.2
        with:
          path: 'android/app'
          file: 'google-services.json'
          content: ${{ secrets.google_services}}
      - name: create key.properties
        uses: 1arp/create-a-file-action@0.2
        with:
          path: 'android'
          file: 'key.properties'
          content: ${{ secrets.key_properties }}