name: CI
on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup secret files
        uses: ./.github/actions/setup_secret_files
        with:
          firebase_options: ${{ secrets.FIREBASE_OPTIONS}}
          google_services: ${{ secrets.GOOGLE_SERVICES}}
          key_properties: ${{ secrets.KEY_PROPERTIES }}
          upload_keystore_b64: ${{ secrets.UPLOAD_KEYSTORE_B64}}
      - name: setup flutter
        uses: ./.github/actions/setup_flutter
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: setup secret files
      uses: ./.github/actions/setup_secret_files
      with:
        firebase_options: ${{ secrets.FIREBASE_OPTIONS}}
        google_services: ${{ secrets.GOOGLE_SERVICES}}
        key_properties: ${{ secrets.KEY_PROPERTIES }}
        upload_keystore_b64: ${{ secrets.UPLOAD_KEYSTORE_B64}}
    - name: setup flutter
      uses: ./.github/actions/setup_flutter
    - run: flutter build apk -t lib/main_dev.dart --flavor=dev --release
    - name: upload artifact to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        token: ${{secrets.FIREBASE_TOKEN}}
        groups: testers
        file: build/app/outputs/flutter-apk/app-dev-release.apk