name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  create_firebase_options:
    name: Create Firebase Options
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: "finnp/create-file-action@master"
          env:
            FILE_NAME: "dir/fileName.txt"
            FILE_DATA: "file content"
  flutter_test:
    needs: create_firebase_options
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test

  build:
    needs: create_firebase_options
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: "12.x"
    - name: build release 
      uses: subosito/flutter-action@v1
      with:
        channel: "stable"
    - run: flutter build apk -t lib/main_dev.dart --flavor=dev
    - name: upload artifact to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        token: ${{secrets.FIREBASE_TOKEN}}
        groups: testers
        file: build/app/outputs/flutter-apk/app-dev-release.apk