name: CI
on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup secret files
        uses: EQSP-Task-Manager/frontend/.github/workflows/setup-secret-files.yml@release-configuration
        with:
          firebase_options: ${{ secrets.FIREBASE_OPTIONS}}
          google_services: ${{ secrets.GOOGLE_SERVICES}}
          key_properties: ${{ secrets.KEY_PROPERTIES}}
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: setup secret files
      uses: EQSP-Task-Manager/frontend/.github/workflows/setup-secret-files.yml@release-configuration
      with:
        firebase_options: ${{ secrets.FIREBASE_OPTIONS}}
        google_services: ${{ secrets.GOOGLE_SERVICES}}
        key_properties: ${{ secrets.KEY_PROPERTIES}}
    - uses: actions/setup-java@v1
      with:
        java-version: "12.x"
    - name: build release 
      uses: subosito/flutter-action@v1
      with:
        channel: "stable"
    - run: flutter build apk -t lib/main_dev.dart --flavor=dev --release
    - name: upload artifact to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        token: ${{secrets.FIREBASE_TOKEN}}
        groups: testers
        file: build/app/outputs/flutter-apk/app-dev-release.apk