on: [workflow_call]

jobs:
  setup_secret_files:
    name: Setup secret files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: create firebase options
        uses: 1arp/create-a-file-action@0.2
        with:
          path: 'lib'
          file: 'firebase_options.dart'
          content: ${{ secrets.FIREBASE_OPTIONS}}
      - name: create google services
        uses: 1arp/create-a-file-action@0.2
        with:
          path: 'android/app'
          file: 'google-services.json'
          content: ${{ secrets.GOOGLE_SERVICES}}
      - name: create key.properties
        uses: 1arp/create-a-file-action@0.2
        with:
          path: 'android'
          file: 'key.properties'
          content: ${{ secrets.KEY_PROPERTIES }}